{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-maven-plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "org.apache.maven.plugin-tools",
          "module": "maven-plugin-annotations",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-core",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-maven-plugin-0.1.0.jar",
          "url": "brazier-maven-plugin-0.1.0.jar",
          "size": 21230,
          "sha512": "cf5f374f9df713d721b015940228eb291312281bee2ccb2e69a0373c614e7602381fc3cb37eef79cf377126d4907cd95f4ad0c804ad91c701ae68fe7b594276a",
          "sha256": "3daa991cd3a72b6789d316ba71ea5b47ef7958473d57d0cad15abe885ba03c55",
          "sha1": "afac4572fbe5d188cfa4ba3c435b0e275b2f0f53",
          "md5": "acbad8f5d33d936473fc4f2b81c4a398"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-tooling",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-wasm-gc-deobfuscator",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-maven-plugin-0.1.0.jar",
          "url": "brazier-maven-plugin-0.1.0.jar",
          "size": 21230,
          "sha512": "cf5f374f9df713d721b015940228eb291312281bee2ccb2e69a0373c614e7602381fc3cb37eef79cf377126d4907cd95f4ad0c804ad91c701ae68fe7b594276a",
          "sha256": "3daa991cd3a72b6789d316ba71ea5b47ef7958473d57d0cad15abe885ba03c55",
          "sha1": "afac4572fbe5d188cfa4ba3c435b0e275b2f0f53",
          "md5": "acbad8f5d33d936473fc4f2b81c4a398"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-plugin-0.1.0-sources.jar",
          "url": "brazier-maven-plugin-0.1.0-sources.jar",
          "size": 7539,
          "sha512": "fb241fdeaf5aa3160ef8e498193986b3c20a0f3060331f21e781fff5b23724c1cd4a77ce66c71b2ccddcd4979ea2d0ffbe5b4ac1d874b2e145ca90d126408452",
          "sha256": "415f8d84af32c7e7bd089a5deb085e8370b0b27d631e72c407a94c27a6f5992d",
          "sha1": "d4f00e6c5ee8786210f1a676b4ad6235d3fdae04",
          "md5": "918916cd9a3fe010a22e89c147af91f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-plugin-0.1.0-javadoc.jar",
          "url": "brazier-maven-plugin-0.1.0-javadoc.jar",
          "size": 89964,
          "sha512": "454be407b57e138adc3f796c26c2f5ef34feb3a36a11439adc3cf3ad0a939dfad6f5553d1023ece57bd582f3d14f880fb7472c9f63406b93e6ab132ea6876c6d",
          "sha256": "821b19c6ee849cbe6b1b39f383c987957b804eb0ef75876a676a56cbe842ff7d",
          "sha1": "1f3d431ff699d4423bd65542a5dd37c1ab13d5ed",
          "md5": "e958c8e0e46fad6c3c23ce82cd3a97aa"
        }
      ]
    }
  ]
}
