{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-maven-webapp",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0.jar",
          "url": "brazier-maven-webapp-0.2.0.jar",
          "size": 4254,
          "sha512": "ba11323e3c460b8c06cf197063d04a415cea449e4ea00496279c675ad1e8fb90fbc29e4cd59d12163979de4fea93c8dfdba7dfba32af9a8484b9065945fe99a4",
          "sha256": "f2248720ac605e61c095b808a980e7914701369f15e393b3c880ca1dfc64a13a",
          "sha1": "48f34138a0426f67c60a882b34647749a377260d",
          "md5": "e706113fd746467a6ef2cc8f3fa22f08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0.jar",
          "url": "brazier-maven-webapp-0.2.0.jar",
          "size": 4254,
          "sha512": "ba11323e3c460b8c06cf197063d04a415cea449e4ea00496279c675ad1e8fb90fbc29e4cd59d12163979de4fea93c8dfdba7dfba32af9a8484b9065945fe99a4",
          "sha256": "f2248720ac605e61c095b808a980e7914701369f15e393b3c880ca1dfc64a13a",
          "sha1": "48f34138a0426f67c60a882b34647749a377260d",
          "md5": "e706113fd746467a6ef2cc8f3fa22f08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0-sources.jar",
          "url": "brazier-maven-webapp-0.2.0-sources.jar",
          "size": 4035,
          "sha512": "1ab8886bc132dfe3cfac6136090196b7a0bcfe55120bc3a3af9565416c0c2ee9b97d13c6763d89a1da7b0e8dc41a03ddbb38b986ee342f257cc4374277eef22f",
          "sha256": "a6c995cc5b4a45d77269fe698128c2b79d93b97126b8cea7abeba66ce99a7edb",
          "sha1": "b34b66c2c1ca6436bda70b28c5b3c1540da9fac9",
          "md5": "857eeac06ba8f32c43a10b23b740cdbd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0-javadoc.jar",
          "url": "brazier-maven-webapp-0.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
