{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-devserver",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brazier-devserver-0.1.0.jar",
          "url": "brazier-devserver-0.1.0.jar",
          "size": 73740,
          "sha512": "c15784ce76601c9e1c631231861221e615bb2036186c4844f3ab06bba32773a13909560bc6f7b75c06747abcafe122a198b119a4cdf5a32ea044d7fa18ef48ce",
          "sha256": "38cc86c361ef3869a4b5be25a1c0763510ae7230f03ea4438832026da1a8dfdd",
          "sha1": "7f25865bedef53de5aeaaad7bc2f30e0c3366232",
          "md5": "8b5ff606c701edcb64f4de6c298b68f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-tooling",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "12.1.9"
          }
        },
        {
          "group": "org.eclipse.jetty.ee10",
          "module": "jetty-ee10-servlet",
          "version": {
            "requires": "12.1.9"
          }
        },
        {
          "group": "org.eclipse.jetty.ee10.websocket",
          "module": "jetty-ee10-websocket-jetty-server",
          "version": {
            "requires": "12.1.9"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "jetty-websocket-jetty-client",
          "version": {
            "requires": "12.1.9"
          }
        },
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-devserver-0.1.0.jar",
          "url": "brazier-devserver-0.1.0.jar",
          "size": 73740,
          "sha512": "c15784ce76601c9e1c631231861221e615bb2036186c4844f3ab06bba32773a13909560bc6f7b75c06747abcafe122a198b119a4cdf5a32ea044d7fa18ef48ce",
          "sha256": "38cc86c361ef3869a4b5be25a1c0763510ae7230f03ea4438832026da1a8dfdd",
          "sha1": "7f25865bedef53de5aeaaad7bc2f30e0c3366232",
          "md5": "8b5ff606c701edcb64f4de6c298b68f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-devserver-0.1.0-sources.jar",
          "url": "brazier-devserver-0.1.0-sources.jar",
          "size": 23372,
          "sha512": "a1d516c914dc5fe2504b1fdb8baaebad32356b7ab9773c51b2390a643a409622c4255b92540cc3b217e6e54a214db1113b749c9a97064d6682102ce7e8d12dba",
          "sha256": "40879bac1dab9a9415fd5d6895e7fe1193523a35d0434573f2bd12becaf342f9",
          "sha1": "035ce5259a045b650b98eedb7674202e70ac7025",
          "md5": "c85961a56fd287e01d695fbe2eee84f3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-devserver-0.1.0-javadoc.jar",
          "url": "brazier-devserver-0.1.0-javadoc.jar",
          "size": 113546,
          "sha512": "2e44c2e0e86c1771738bdb88c176ddbe595811b46f0f465cdfe7a4b20c15452948917ba2b8e16f8e85ba2dc0890a68fbc9640126a1a45f1968f5292568c894ca",
          "sha256": "dd28e3a791b25212b443e9c3f84e5d2ed2ff9c3a576185c255c871fd1ebf4559",
          "sha1": "5878fef85b59b3fd0bdf17beecc51dee409203a9",
          "md5": "35cf46ea6041fda00a9f503ad83c9a88"
        }
      ]
    }
  ]
}
