{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-relocated-libs-asm",
    "version": "0.2.0-rc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-relocated-libs-asm-0.2.0-rc.jar",
          "url": "brazier-relocated-libs-asm-0.2.0-rc.jar",
          "size": 126021,
          "sha512": "348e72594878a7e6c46992308002b55eb25db1d371426a0cf482a6959b495ba63b3574c4ec4273a3a7751eb95b9a363e772b7410e1570cdae4103c480a29b6eb",
          "sha256": "d8119ffcdc44fc0493092ec40da7b6898fe6cccdd1e5d840237291e0ba7216a4",
          "sha1": "b13dd21ebd6bf590bdda2202e1bb07d2893cef05",
          "md5": "416774f00d204f80a1e2320048220f84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-relocated-libs-asm-0.2.0-rc.jar",
          "url": "brazier-relocated-libs-asm-0.2.0-rc.jar",
          "size": 126021,
          "sha512": "348e72594878a7e6c46992308002b55eb25db1d371426a0cf482a6959b495ba63b3574c4ec4273a3a7751eb95b9a363e772b7410e1570cdae4103c480a29b6eb",
          "sha256": "d8119ffcdc44fc0493092ec40da7b6898fe6cccdd1e5d840237291e0ba7216a4",
          "sha1": "b13dd21ebd6bf590bdda2202e1bb07d2893cef05",
          "md5": "416774f00d204f80a1e2320048220f84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-relocated-libs-asm-0.2.0-rc-sources.jar",
          "url": "brazier-relocated-libs-asm-0.2.0-rc-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-relocated-libs-asm-0.2.0-rc-javadoc.jar",
          "url": "brazier-relocated-libs-asm-0.2.0-rc-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
