{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-maven-webapp",
    "version": "0.2.0-rc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0-rc.jar",
          "url": "brazier-maven-webapp-0.2.0-rc.jar",
          "size": 4257,
          "sha512": "3b8aa1304856cb7507b8e5c64d9dde75c264350436997fc13df565db35b880c611e2a3bdbfae423d0d0af480a29f402f42d57d9af3c4135b942bc3e56f9e2ee4",
          "sha256": "7c0a122182253c5d77bf74a25e7101066c4d89a15416e42c6cb9418503adeb02",
          "sha1": "3c0b1467fd0842b5a2d9ca71ecbfbf6b3f655f2d",
          "md5": "8938406f99f5b3e3795b2e36c5842d10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0-rc.jar",
          "url": "brazier-maven-webapp-0.2.0-rc.jar",
          "size": 4257,
          "sha512": "3b8aa1304856cb7507b8e5c64d9dde75c264350436997fc13df565db35b880c611e2a3bdbfae423d0d0af480a29f402f42d57d9af3c4135b942bc3e56f9e2ee4",
          "sha256": "7c0a122182253c5d77bf74a25e7101066c4d89a15416e42c6cb9418503adeb02",
          "sha1": "3c0b1467fd0842b5a2d9ca71ecbfbf6b3f655f2d",
          "md5": "8938406f99f5b3e3795b2e36c5842d10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0-rc-sources.jar",
          "url": "brazier-maven-webapp-0.2.0-rc-sources.jar",
          "size": 4035,
          "sha512": "1ab8886bc132dfe3cfac6136090196b7a0bcfe55120bc3a3af9565416c0c2ee9b97d13c6763d89a1da7b0e8dc41a03ddbb38b986ee342f257cc4374277eef22f",
          "sha256": "a6c995cc5b4a45d77269fe698128c2b79d93b97126b8cea7abeba66ce99a7edb",
          "sha1": "b34b66c2c1ca6436bda70b28c5b3c1540da9fac9",
          "md5": "857eeac06ba8f32c43a10b23b740cdbd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-maven-webapp-0.2.0-rc-javadoc.jar",
          "url": "brazier-maven-webapp-0.2.0-rc-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
