{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-interop",
    "version": "0.2.0-rc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brazier-interop-0.2.0-rc.jar",
          "url": "brazier-interop-0.2.0-rc.jar",
          "size": 12645,
          "sha512": "e19a1ff9dfb0a6cc61c2e82315e11e86568b8b802e3d948613e77a97d1c367ac6c7502ca48890b9482eb98f527a22720241c64a1feda4c7be9372dd62ea2d053",
          "sha256": "c0dcb4ffd87634d8d08ce1d068acdd6e6dcde95a5939f22c6e7580af21185daf",
          "sha1": "1f31d3c7adaebd86fa8f3f98f7330b7343bf4079",
          "md5": "4fb2d6deff605b270d3c70a8ea437232"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-interop-0.2.0-rc.jar",
          "url": "brazier-interop-0.2.0-rc.jar",
          "size": 12645,
          "sha512": "e19a1ff9dfb0a6cc61c2e82315e11e86568b8b802e3d948613e77a97d1c367ac6c7502ca48890b9482eb98f527a22720241c64a1feda4c7be9372dd62ea2d053",
          "sha256": "c0dcb4ffd87634d8d08ce1d068acdd6e6dcde95a5939f22c6e7580af21185daf",
          "sha1": "1f31d3c7adaebd86fa8f3f98f7330b7343bf4079",
          "md5": "4fb2d6deff605b270d3c70a8ea437232"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-interop-0.2.0-rc-sources.jar",
          "url": "brazier-interop-0.2.0-rc-sources.jar",
          "size": 17902,
          "sha512": "8450ca3062fbcf51a4c2a24a6859a3b97d20564d909edfc0c94d542e06ff294b6caf17965806a2929e1abbb60cf0c45a1e30f00f4d00ad324f4a530a28078346",
          "sha256": "5dff7691aa71c1475c16152da96a4e31023bb605d0a5ca16423323723814005b",
          "sha1": "691387365e0ce865b92bfd3b7eb952fc8f98f327",
          "md5": "535f5b8893213b8f9ae81c58bb961d6e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-interop-0.2.0-rc-javadoc.jar",
          "url": "brazier-interop-0.2.0-rc-javadoc.jar",
          "size": 137212,
          "sha512": "7b7a4d7a81c8ed3786e7b67db79389e437369e1b8e42234eb6f0ce3f3ef0d829c2bc7b3b7eacba98d86eca1f8392d600cb1c7a1373fdbc77bdbee2f8fad4668e",
          "sha256": "9f9bfe72e551390b4cd8f38920b2dc8f689ba08a8fb7b385c95d10694547f624",
          "sha1": "7d49355f89085101e0de53a7544990fdda8a661d",
          "md5": "f182d872908516f48c19563301cae155"
        }
      ]
    }
  ]
}
