{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-junit",
    "version": "0.2.0-rc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brazier-junit-0.2.0-rc.jar",
          "url": "brazier-junit-0.2.0-rc.jar",
          "size": 93030,
          "sha512": "2ec7bfb064c07b65edf56e057a5f14afbf3787e159585f5dedc9f804fcf9bac01ab2690cf6fba20e1ef6390094f3582e5e8d4f3b49be0f6b8c7aac4ed868d4cf",
          "sha256": "75f273135586604c91bbe5c5b7b2d6c2ed8043fa24523203b3c67ffc2a3406d4",
          "sha1": "bc85ff2fdcd453e138583ffeacc6a69acff26943",
          "md5": "b9ff4fc87b85bbea2c970504e9bce243"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-core",
          "version": {
            "requires": "0.2.0-rc"
          }
        },
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-tooling",
          "version": {
            "requires": "0.2.0-rc"
          }
        },
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-browser-runner",
          "version": {
            "requires": "0.2.0-rc"
          }
        },
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-wasm-gc-deobfuscator",
          "version": {
            "requires": "0.2.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-junit-0.2.0-rc.jar",
          "url": "brazier-junit-0.2.0-rc.jar",
          "size": 93030,
          "sha512": "2ec7bfb064c07b65edf56e057a5f14afbf3787e159585f5dedc9f804fcf9bac01ab2690cf6fba20e1ef6390094f3582e5e8d4f3b49be0f6b8c7aac4ed868d4cf",
          "sha256": "75f273135586604c91bbe5c5b7b2d6c2ed8043fa24523203b3c67ffc2a3406d4",
          "sha1": "bc85ff2fdcd453e138583ffeacc6a69acff26943",
          "md5": "b9ff4fc87b85bbea2c970504e9bce243"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-junit-0.2.0-rc-sources.jar",
          "url": "brazier-junit-0.2.0-rc-sources.jar",
          "size": 50094,
          "sha512": "16c7f5201c539421cb6988284eabe3ecee0409ba6541fde6193c75c96836998fe82dd674662ebefcfb4a57cfaccaa45503d6af9cc476c4a635a216afd358ed3e",
          "sha256": "41d2b4ad42c7adb305ce44e216e0d97c53f9c219dc97218d1c303382576464a8",
          "sha1": "1b4c50386e609ee9ca50648460e6b6916926a9d9",
          "md5": "121ca45fc9d708e8c69580b522991b40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-junit-0.2.0-rc-javadoc.jar",
          "url": "brazier-junit-0.2.0-rc-javadoc.jar",
          "size": 109962,
          "sha512": "cbe86449d03d2e67c35e08dbf5bd82fa2d3aae6e76bf92f17740f702b4b3e830703f1e6576f5e093da478458f21d7c8c227c9a5b6e7cbb26198120704320e0da",
          "sha256": "f83bcb1691817077a12b1395a530d28e54c223a6d0ccb71a21494f05a68a8fcc",
          "sha1": "58f629780922814f87045d5aa29bc08ea130a8e7",
          "md5": "7cafae63d695065834ddc1f9d6aa3113"
        }
      ]
    }
  ]
}
