{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-relocated-libs-rhino",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-relocated-libs-rhino-0.2.0.jar",
          "url": "brazier-relocated-libs-rhino-0.2.0.jar",
          "size": 1427030,
          "sha512": "27bf00e3e85bf46fe7515213c725189407b20b0d5151cd831f0c3b51fe237e7e2b4ffde84874faab51aadfbf7780b7db99804ca2ab9590da9b142d396dc5d73f",
          "sha256": "0ed5b988e24006b1c19b6f20d8ce143b35dba344bc1d1e8df5df74822890ffe3",
          "sha1": "227e21561b91f5ed5bb41fbcf196d29686091444",
          "md5": "56d67aa17e46b86f36a1879d819b7516"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-relocated-libs-rhino-0.2.0.jar",
          "url": "brazier-relocated-libs-rhino-0.2.0.jar",
          "size": 1427030,
          "sha512": "27bf00e3e85bf46fe7515213c725189407b20b0d5151cd831f0c3b51fe237e7e2b4ffde84874faab51aadfbf7780b7db99804ca2ab9590da9b142d396dc5d73f",
          "sha256": "0ed5b988e24006b1c19b6f20d8ce143b35dba344bc1d1e8df5df74822890ffe3",
          "sha1": "227e21561b91f5ed5bb41fbcf196d29686091444",
          "md5": "56d67aa17e46b86f36a1879d819b7516"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-relocated-libs-rhino-0.2.0-sources.jar",
          "url": "brazier-relocated-libs-rhino-0.2.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-relocated-libs-rhino-0.2.0-javadoc.jar",
          "url": "brazier-relocated-libs-rhino-0.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
