{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-extension-spi",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-extension-apis",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-extension-spi-0.2.0.jar",
          "url": "brazier-extension-spi-0.2.0.jar",
          "size": 16561,
          "sha512": "4e03daa47fd9a379448003ee6865cd1e70a7e676de86360e273fac6450c1ceae70ef78b14780f74f25bf43a3864218b074b7ce8a6867dd1783ab847359d1c885",
          "sha256": "27d3585e8133a50d991890d1ef2a8a9df57eafb7986f86f69c5016c373984675",
          "sha1": "5f064018ed9893659fd7204c6048c8fa0070766d",
          "md5": "81a2a74cad1801ac1edfa5b8313a59b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-extension-spi-util",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-extension-apis",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-extension-spi-0.2.0.jar",
          "url": "brazier-extension-spi-0.2.0.jar",
          "size": 16561,
          "sha512": "4e03daa47fd9a379448003ee6865cd1e70a7e676de86360e273fac6450c1ceae70ef78b14780f74f25bf43a3864218b074b7ce8a6867dd1783ab847359d1c885",
          "sha256": "27d3585e8133a50d991890d1ef2a8a9df57eafb7986f86f69c5016c373984675",
          "sha1": "5f064018ed9893659fd7204c6048c8fa0070766d",
          "md5": "81a2a74cad1801ac1edfa5b8313a59b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-extension-spi-0.2.0-sources.jar",
          "url": "brazier-extension-spi-0.2.0-sources.jar",
          "size": 10715,
          "sha512": "74c0757a09cee1b6447d0b73fd02a34ef278b08ac969ca706fe486ebc1d7f137451cb6bde7756179aa3d70480062d02233f264fed0f2a6ae3a3ecfbbe81218ef",
          "sha256": "b25e2860af4355f832c426b8de84c6f964cb06b11d984ba6f3b59d103c869bef",
          "sha1": "8867acfcd61e1449d5d11865ef5be9b7507447cd",
          "md5": "3900f40b25208ff3777ceac36f62ec40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-extension-spi-0.2.0-javadoc.jar",
          "url": "brazier-extension-spi-0.2.0-javadoc.jar",
          "size": 118322,
          "sha512": "497a2c160397a1ed335f4199eda088c57c0db9e48374987583b679246c49977be99a2c0b7f1d6056baa92a106a5cbdac1c0e30d15ab99a8f096708f92a09272c",
          "sha256": "2b37bef88c46a815490e6b5c84e651afeb478a9e992f97b23c1ac12800276b07",
          "sha1": "e6a2588d36ac24a1504bf35917e63f3570c1c6a1",
          "md5": "ab272b7f854a43b75840f98d6dfb580d"
        }
      ]
    }
  ]
}
