{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.intisy.brazier",
    "module": "brazier-extras-slf4j",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brazier-extras-slf4j-0.2.0.jar",
          "url": "brazier-extras-slf4j-0.2.0.jar",
          "size": 7251,
          "sha512": "37795e9df2c2bf5365768e60fb52e820bd884f17ff550bbef72d01f025b2cbdd06e7df05a0f6b53c14d739963f0554e594ec9415c815307b12d527638b954e69",
          "sha256": "4a04f8a13d50ec6829d5a994b2f1ed83736781d9d9654fade46c49ba7ede206f",
          "sha1": "f4b331de531c02c870395afa5da1dce521f102e7",
          "md5": "f8006c3b44d6afa91a1ece5cbc4c1224"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.intisy.brazier",
          "module": "brazier-jso",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "brazier-extras-slf4j-0.2.0.jar",
          "url": "brazier-extras-slf4j-0.2.0.jar",
          "size": 7251,
          "sha512": "37795e9df2c2bf5365768e60fb52e820bd884f17ff550bbef72d01f025b2cbdd06e7df05a0f6b53c14d739963f0554e594ec9415c815307b12d527638b954e69",
          "sha256": "4a04f8a13d50ec6829d5a994b2f1ed83736781d9d9654fade46c49ba7ede206f",
          "sha1": "f4b331de531c02c870395afa5da1dce521f102e7",
          "md5": "f8006c3b44d6afa91a1ece5cbc4c1224"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-extras-slf4j-0.2.0-sources.jar",
          "url": "brazier-extras-slf4j-0.2.0-sources.jar",
          "size": 5674,
          "sha512": "286513cde6be514e8862590541cc91e22c7ce2c990f8b2e847d5fb2052763e7481bd1d8fc3aafb2f1592fd05a816fef7648799acdf68405817881abd0f10caa5",
          "sha256": "9fbd786476ff048e70617271dfb13ae9730f36f7408a1bd5985108ec79a3e4d2",
          "sha1": "f2aac9c5cf65961c3facb54cf48125febb8e0b27",
          "md5": "04855502fb38201f342e50d9670434f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brazier-extras-slf4j-0.2.0-javadoc.jar",
          "url": "brazier-extras-slf4j-0.2.0-javadoc.jar",
          "size": 94092,
          "sha512": "648921ed7d58865497035695a2fe3833dd1d4214b27b93331827d30a506008030bd021f3d6ecf6b06776267d5f7bb4fa185ece74b84494571bd1121005a8142e",
          "sha256": "9bc294eb56eaf74efc7d68f556ab711c87f38d3743b84a0a871bc6ae2e8955d0",
          "sha1": "87a02b9694b913b60156f9e1491ed930ddf7b253",
          "md5": "f0f9954e1deab0f934939c4f980eb6cb"
        }
      ]
    }
  ]
}
